server:
  port: 9000
  context-path: /beerhouse
  
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost/craftBeer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    